---
execute:
  include: false
  echo: false
---

```{r, include = FALSE}
library(ggplot2)
library(dplyr)
library(plotly)
```


```{r}
cars <- read.csv("../../data/clean/crime_dc.csv")
```

```{r, include = FALSE}
library(lubridate)
# Parse the date strings into POSIXct objects (date-time class)
cars$date <- ymd_hms(cars$report_date)
cars$date <- as.Date(cars$date)
```




```{r, include = TRUE, echo = FALSE}
# Calculate year-over-year growth percentage
cars_aggregated <- cars %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  summarize(theft_count = n()) %>%
  mutate(yoy_growth = (theft_count / lag(theft_count, default = first(theft_count))) - 1)

# Filter out the data for the year 2024
cars_aggregated <- cars_aggregated %>%
  filter(year < 2024)

# Create text for tooltip
cars_aggregated$tooltip_text <- paste("Year:", cars_aggregated$year, "<br>",
                                      "Car Theft Count:", cars_aggregated$theft_count, "<br>",
                                      "YoY Growth:", paste0(round(cars_aggregated$yoy_growth * 100, 1), "%"))

t <- list(
  family = "Impact",
  size = 18,
  color = "black")

t1 <- list(
  family = "Impact",
  size = 24,
  color = "black")

# Plot interactive chart
plot_ly(data = cars_aggregated, x = ~factor(year), y = ~theft_count, type = 'bar',
        text = ~tooltip_text,  # Set the text to tooltip_text column
        texttemplate = "",  # Empty string for texttemplate to remove text on bars
        hoverinfo = 'text',
        marker = list(color = '#493FB3', line = list(color = 'black'))) %>%
  layout(xaxis = list(title = list(text = "Year", font = t)), 
         yaxis = list(title = list(text = "Car Theft Count", font = t)),
         title = list(text = "Yearly Counts of Car Thefts in Washington DC", font = t1, y = 0.9))
```