---
output: html_document
execute:
  echo: false
engine: knitr
format:
    html:
        embed_resources: true
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
library(tidyverse)
library(ggplot2)
library(lubridate)
library(plotly)
library(readr)
reticulate::use_condaenv("dsan5200", required = TRUE)
color_palette <- c("#A8C4FF", "#A56A6E", "#89B587", "#6A7FAB", "#FFDAA1", "#EFA4D6", "#7C5FBC", "#F2B37A")

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
raw_arrests <- read_csv("../../data/clean/adult_arrests_dc.csv")
raw_juvenile <- read_csv("../../data/clean/juvenile_arrests_dc.csv")
```

```{r}
arrests_df <- raw_arrests %>% 
  select(-c(arrestee_type, ccn, arrest_number_number, arrest_date))
```

```{r}
description <- arrests_df %>%
  filter(arrest_category %in% c("Property Crimes")) %>% 
  group_by(charge_description) %>% 
  summarize(total = n())
```

```{r}
adult_by_crime <- arrests_df %>% 
  group_by(charge_description) %>% 
  summarize(total = n()) %>% 
  arrange(desc(total))

juvenile_by_crime <- raw_juvenile %>% 
  group_by(top_charge_description) %>% 
  summarize(total = n()) %>% 
  arrange(desc(total))

total_by_crime <- full_join(adult_by_crime, 
                            juvenile_by_crime, 
                            by = c("charge_description" = "top_charge_description")) %>% 
  rename(adult = total.x, 
         juvenile = total.y,
         charge = charge_description) %>% 
  replace_na(list(adult = 0, juvenile = 0)) %>%
  filter(adult > 200 | juvenile > 20) %>% 
  mutate(adult = adult / sum(adult),
         juvenile = juvenile / sum(juvenile),
         difference = adult - juvenile,
         fill_color = ifelse(charge != "Unauthorized Use Of A Vehicle", "grey", "firebrick")) %>% 
  arrange(desc(difference))

p1 <- ggplot(total_by_crime, aes(x = reorder(charge, -difference), 
                                 y = difference, 
                                 fill = fill_color,
                                 label = charge)) +
  geom_bar(stat = "identity", position = "dodge", alpha = 1) +
  labs(y = "Proportion of Arrests",
       x = "",
       title = "Difference in Proportion of Arrests by Charge",
       subtitle = "(Adult - Juvenile)",
       color = "Group") +
  scale_fill_manual(values = c("#D34B7F", "grey")) +
  theme_minimal() +
  theme(legend.position = "none",
        axis.text.x = element_blank(),
        panel.grid.major.x = element_blank()) +
  annotate("text", 
           x = 60, y = -.075, 
           label = "Unauthorized Use Of A Vehicle", 
           family = "Impact",
           size = 4, 
           color = "firebrick",
           angle = 0) +
  annotate("text", 
           x = 7, y = 0.14, 
           label = "More Adults", 
           size = 4, 
           color = "black",
           family = "Impact",
           angle = 0) +
  annotate("text", 
           x = 7, y = -0.14, 
           label = "More Juveniles", 
           size = 4, 
           color = "black",
          family = "Impact",
           angle = 0) +
           theme(
          axis.line = element_line(colour = "black", linewidth = 0.5),
          title = element_text(family = "Impact", size = 20),
          axis.title = element_text(family = "Impact", size = 15),
        )

tooltip_text <- paste("reorder(charge, -difference): ", total_by_crime$charge, "<br>",
                 "difference: ", total_by_crime$difference, "<br>")

ggplotly(p1, tooltip = "charge")
```